//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T8MM.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("T8MM.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string KEY_MODS {
            get {
                return ResourceManager.GetString("KEY_MODS", resourceCulture);
            }
        }
        
        public static string KEY_SETTINGS {
            get {
                return ResourceManager.GetString("KEY_SETTINGS", resourceCulture);
            }
        }
        
        public static string KEY_LANGUAGE {
            get {
                return ResourceManager.GetString("KEY_LANGUAGE", resourceCulture);
            }
        }
        
        public static string KEY_USER_API {
            get {
                return ResourceManager.GetString("KEY_USER_API", resourceCulture);
            }
        }
        
        public static string KEY_GAME_ROOT_FOLDER {
            get {
                return ResourceManager.GetString("KEY_GAME_ROOT_FOLDER", resourceCulture);
            }
        }
        
        public static string KEY_GAME_ROOT_FOLDER_TIPS {
            get {
                return ResourceManager.GetString("KEY_GAME_ROOT_FOLDER_TIPS", resourceCulture);
            }
        }
        
        public static string KEY_REFRESH {
            get {
                return ResourceManager.GetString("KEY_REFRESH", resourceCulture);
            }
        }
        
        public static string KEY_LOADING {
            get {
                return ResourceManager.GetString("KEY_LOADING", resourceCulture);
            }
        }
        
        public static string KEY_SAVE_BUTTON {
            get {
                return ResourceManager.GetString("KEY_SAVE_BUTTON", resourceCulture);
            }
        }
    }
}
